platform :ios, '12.0'
use_frameworks!

workspace 'App'  # ← これを追加（Capacitor の Xcode workspace を指定）

target 'App' do
  capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
end
